language: go
go:
 - 1.1
 - 1.2
 - 1.3
 - release
 - tip

install:
 - go get github.com/hashicorp/golang-lru
 - go get github.com/BurntSushi/toml
 - go get github.com/seiflotfy/cuckoofilter

script:
 - go build main.go
