# this is where top level info is stored for the counter manager we could also use a boltDB in the DataDir but this would make it harder to sync over replicas since not all replicas will hold the all the counters.
info_dir = "~/.skizze/info"

# this is where the data is stored either as json or .count (pure bytes)
data_dir = "~/.skizze/data"

# is needed for the raw bytes storage since we can split them up and not have it all in memory at once.
slice_size = 5

# num of counters in cache
cache_size = 250

# number slices in the slice cache
slice_cache_size = 1

# the port number for the server
port = 3596

# Treshold for saving a sketch to disk
save_threshold_seconds = 3600
